# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  - develop
  - release/*

pr:
  - master
  - develop
  - release/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: '1.0.1'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  name: sourceVersion
  inputs:
    targetType: 'inline'
    script: |
      # Get package version.
      $version = (Get-Content -Raw -Path AssemblyVersion.json | ConvertFrom-Json).version
      $majorVersion = ($version | ConvertFrom-String -Delimiter "\.").P1
      $minorVersion = ($version | ConvertFrom-String -Delimiter "\.").P2
      $patchVersion = ($version | ConvertFrom-String -Delimiter "\.").P3
      echo "##vso[task.setvariable variable=majorVersion;isOutput=true]$majorVersion"
      echo "##vso[task.setvariable variable=minorVersion;isOutput=true]$minorVersion"
      echo "##vso[task.setvariable variable=patchVersion;isOutput=true]$patchVersion"

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: $(sourceVersion.majorVersion)
    minorVersion: $(sourceVersion.minorVersion)
    patchVersion: $(sourceVersion.patchVersion)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'DesignPatterns'
    publishLocation: 'Container'
